# Generated by Django 5.0.4 on 2024-05-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=14)),
                ('fecha_contrato', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='periodistas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPeriodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='noticias')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=5000, null=True)),
                ('periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodista')),
                ('TipoNoticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiponoticia')),
            ],
        ),
        migrations.AddField(
            model_name='periodista',
            name='TipoPeriodista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoperiodista'),
        ),
    ]
